build:
  script:
    - cargo build --verbose --release
    - cargo test -- verbose
  tags:
    - rust
pages:
  stage: deploy
  script:
    - cargo doc --verbose
    - mkdir -p public/
    - cp -r target/doc/* public/
  artifacts:
    paths:
    - public
  only:
  - master